db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://rm-bp198u9b681a17b7jqo.mysql.rds.aliyuncs.com:3306/pet_home?useSSL=false&serverTimezone=Asia/Shanghai
db.username=cheese
db.password=Pethome123!
db.initialSize=5
db.maxTotal=20
db.maxIdle=10
db.minIdle=5
db.maxWaitMillis=5000